### ISSUE TITLE
Demo this repo?

### ISSUE THREAD

**Issue by SaileshBechar** [tcapelle/metnet_pytorch#1]
Hello Thomas,

I am really interested in your code here and would love to test it out! Is there an easy way to do this? I am not sure how to pass images in the input as it is done in the MetNet paper.

Kind regards,
Sailesh

**Comment by tcapelle** [comment]
there is not...
This repo is only an architecture definition in pytorch, hoping that someone with time and data would try to train one of this monsters. I know that the guys at OCR have played with it, but with no sucess [here](https://github.com/openclimatefix/satflow).
You are welcome to try to make it work/modify/train... :)
